# Generated by Django 6.0.4 on 2026-04-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
